GET http://localhost:8080/spring-mvc-app/api/v1/products/all

###

GET http://localhost:8080/spring-mvc-app/api/v1/products/4

###

GET http://localhost:8080/spring-mvc-app/api/v1/user/3
Authorization: Basic admin 111

###

POST http://localhost:8080/spring-mvc-app/api/v1/user
Content-Type: application/json
Authorization: Basic root 111

{
  "username": "user111",
  "password": "222",
  "email": "xxx@outlook.com",
  "age": 33
}

###

POST http://localhost:8080/spring-mvc-app/api/v1/products
Content-Type: application/json

{
  "name": "SDD",
  "description": "520 GB",
  "price": 5400
}

###

PUT http://localhost:8080/spring-mvc-app/api/v1/products
Content-Type: application/json

{
  "id": 25,
  "name": "Error",
  "description": "520 GB",
  "price": 3400
}

###

DELETE http://localhost:8080/spring-mvc-app/api/v1/products/12

###

GET http://localhost:8080/spring-mvc-app/api/v1/trash/99

###

PUT http://localhost:8080/spring-mvc-app/api/v1/trash?userId=1&productId=19




